version: "3.5"
services:
    auth_db:
        image: postgres
        restart: always
        env_file:
            - ./app/.env
        expose:
            - "5432"
        volumes: 
            - "./postgres-data/:/var/lib/postgresql/data"

    auth_service:
        restart: always
        env_file:
            - ./app/.env
        build:
            context: ./app
        depends_on: 
            - auth_db
        expose:
            - "8080"

    auth_nginx:
        restart: always
        depends_on: 
            - auth_service
        build:
            context: ./nginx
        ports:
            - "443:443"
